services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID:-950}     # Default to running as truenas_admin user with ID 950
      - PGID=${PGID:-950}     # Default to running as truenas_admin group with ID 950
      - TZ=${TZ:-UTC}
    #  - NVIDIA_VISIBLE_DEVICES=all    # Uncomment to enable this container to see Nvidia GPUs. Useful for troubleshooting.
    
    # Configure any volumes here. You can either do individual volumes for each Dataset or a single volume with everything in it (Not Recommended).
    volumes:
      - ./config:/config     # This is the configuration directory
      - /mnt/<TrueNAS Pool>/Docker-Apps/Code:/Docker/code-server     # This is the Dataset where the compose.yaml file will live.
      - /mnt/<TrueNAS Pool>/Docker-Apps/Traefik:/Docker/traefik
    
    # Uncomment the below to enable Traefik proxy integration.
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.code-server.loadbalancer.server.port=8443
    #   - traefik.http.services.code-server.loadbalancer.server.scheme=http
    #   - traefik.http.routers.code-server.entrypoints=websecure
    #   - traefik.http.routers.code-server.rule=Host(`code.example.net`)
    #   - traefik.http.routers.code-server.tls=true
    #   - traefik.http.routers.code-server.tls.certresolver=cloudflare

    # If using the Traefik integration above then comment the below.
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true