services:
  traefik:
    image: docker.io/library/traefik:v3.5.2
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      # - 8181:8080
      # <--
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/<Storage Pool Name>/Docker-Apps/Traefik/config/:/etc/traefik/:ro
      - /mnt/<Storage Pool Name>/Docker-Apps/Traefik/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=<Cloudflare Token>  # <-- Change this to your Cloudflare API Token
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.httpsonly.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsonly.redirectscheme.permanent=true"
      - "traefik.http.routers.httpsonly.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.httpsonly.middlewares=httpsonly"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.example.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=cloudflare"

networks:
  traefik-proxy:
    name: traefik-proxy
    external: false # Set to false to create a new network with the app. Set to true if you want to use an existing network or make one manually.